plugins:
  - name: bool64/dev
    package: github.com/bool64/dev
    makefiles_path: makefiles
    main: main.mk

  - name: storage
    makefiles_path: makefiles
    main: ../internal/makefiles/main.mk